

```{r}
#Q1
require(jsonlite)
data <- fromJSON('Housing2122.json')
data <- as.data.frame(data)
```

```{r}
#Q2
Sys.setlocale("LC_TIME", "English")
data$date <- gsub("nd|st|th|rd", "", data$date)
data$date <- as.Date(data$date, format = "%d %b %Y")
data$date <- format(data$date, "%e/%m/%Y")
```

```{r}
#Q3
data[is.na(data$sq.),c('sq.')] <- "0s"
data
```



```{r}
#Q4
data$TotalBeds <- as.numeric(mapply(function(x,y){
  if( is.na(x)!= TRUE ){
    return (x)
  }else if(is.na(y) != TRUE){
    return (y)
  }else{return(0)}
}, data$bed, data$beds))
```

```{r}
data$TotalBaths <- as.numeric(mapply(function(x,y){
  if( is.na(x)!= TRUE ){
    return (x)
  }else if(is.na(y) != TRUE){
    return (y)
  }else{return(0)}
}, data$bath, data$baths))

```



```{r}
data$TotalReceptions <- as.numeric(mapply(function(x,y){
  if( is.na(x)!= TRUE ){
    return (x)
  }else if(is.na(y) != TRUE){
    return (y)
  }else{return(0)}
}, data$reception, data$receptions))
```


```{r}
#Q5
require(stringr)
data$FlatType <- str_extract(data$types, "(?<=\\d bed).*?(?= for sale)")
data[is.na(data$FlatType),]$FlatType <- str_extract(data[is.na(data$FlatType),'types'],".*(?= for sale)")
```



```{r}
#æ•´ç†Data
data <- data[,-which(names(data) %in% c('baths', 'beds', 'bed', 'receptions', 'reception', 'bath'))]
```


```{r}
data
```


```{r}
#Q6
write.csv(data,file = 'Project_Housing.csv')
```

